### PR TITLE
Add testing for py35 and pypy.

### PR DESCRIPTION
**Pull request by jhgg**
Because why not? Looks to be passing all tests on my computer.

### CODE REVIEW

**Comment by woodb** [comment]
I agree, why not? Hah. Could also consider adding to [setup.py](https://github.com/dittos/graphqllib/blob/master/setup.py#L42) that these extra versions of Python are supported...

**Comment by jhgg** [comment]
Amazingly enough... the py35 build fails on travis due to some weird errors in pytest. But not on my local python3.5 :|

**Comment by jhgg** [comment]
A solution has been found https://github.com/pytest-dev/pytest/issues/744

**Comment by woodb** [comment]
Yeah it looks like it was fixed in [pytest v2.7.3](http://pytest.org/latest/changelog.html#compared-to-2-7-2), while Travis has `v2.7.2`.

**Comment by jhgg** [comment]
:+1: Looks like it's working now.

**Comment by woodb** [comment]
I've added some [setup.py tweaks](https://github.com/dittos/graphqllib/pull/35#issuecomment-141703530) to this branch as jhgg/graphqllib#1

**Comment by jhgg** [comment]
Merged into this pr @woodb.

**Pull request merged**
