### PR TITLE
Python35+ asyncio executor implementation

### PR DESCRIPTION
**Pull request by mpaolini**
Reusable synchronous code in `graphql.core.executor` is factored out in `graphql.core.executor.base`

Executor implementations interact with synchronous common code using generators.

17 tests fail

### CODE REVIEW

**Comment by mpaolini** [comment]
This relates to #28 as it effectively implements a functional-style pluggable executor model

**Comment by mpaolini** [comment]
please @jhgg let me know if I should going further down this route. Basically it is 99% done.

the core of the sync/async interoperability lies in the four `XXX_gen` generator functions in `graphql.core.executor.base` and the way they interact with `graphql.core.executor` `graphql.contrib.py35_asyncio.executor` implementations.

Downsides:
- the generator's signatures are now a bit awkward (I will definitely improve documentation)

Ups:
- the concrete executor implementation is only around 100 lines of code
- contrib and core executor share **a lot** of code
- maintenance of contrib and core executor is quite easy
- no metaprogramming magic needed
- no complex class inheritance/method overriding needed

So AFAIK this is the best way to keep shared code between a syncronous and an asynchronous implementation.

**Comment by dittos** [comment]
I don't feel good about that sync implementation also should use generators. Would maintaining separate code for async version be hard? It's less likely the executor code to be changed often.

**Comment by mpaolini** [comment]
@dittos it would mean much less shared code, basically we would need to copy and paste code of all functions on the `async` call chain from `graphql.core` to `graphql.contrib.asyncio`

I will try to cook an alternative patch and see how we go

**Comment by jhgg** [comment]
#51 also implements a pluggable asyncio middleware. Perhaps it supersedes this PR?

**Comment by mpaolini** [comment]
Yes I'm retracting this one 'cause it only covers the asyncio case

**Pull request closed without merging**
